name: Deploy to GitHub Pages on Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Token d'authentification fourni automatiquement par GitHub
          publish_dir: ./dist # Le dossier à publier (le dossier de sortie de votre build VueJS)
          publish_branch: gh-pages # La branche cible pour GitHub Pages (créée si elle n'existe pas)
          # cname: example.com # Décommentez et remplacez par votre CNAME si vous utilisez un domaine personnalisé